// Cybex Sentinel — Proxmox Backup Server backup assurance.
import React from "react";
import type { PbsBackup, PbsCoverageFinding, PbsDatastore, PbsTask, Snapshot } from "../api";
import { Card, Chip, Icon, KPI_COLORS, KpiTile, StatusDot } from "../components";
import { EditableGrid, type EditableLayoutValue, type LayoutStore } from "../layouts";
const KPI_LABELS = ["Recent Backups", "Latest Backup", "Datastore Usage", "Coverage Gaps"];
function ageLabel(min: number | null): string { if (min === null) return "never"; if (min < 1) return "just now"; if (min < 60) return `${min}m ago`; if (min < 1440) return `${Math.floor(min / 60)}h ${min % 60}m ago`; return `${Math.floor(min / 1440)}d ago`; }
function backupTone(b: PbsBackup): string { if (b.verification === "failed") return "crit"; if (b.ageMin > 36 * 60 || b.verification === "unverified") return "warn"; return "ok"; }
function findingTone(f: PbsCoverageFinding): string { if (f.tone === "crit" || f.kind === "missing") return "crit"; if (f.tone === "warn" || f.kind === "stale") return "warn"; return "info"; }
function TaskRow({ task }: { task: PbsTask }) { const tone = task.ok ? "ok" : "crit"; return <div className="log-row" style={{ gridTemplateColumns: "72px 96px 1fr 92px 86px" }}><span className="mono">{ageLabel(task.ageMin)}</span><span><Chip tone={tone} dot>{task.status}</Chip></span><span className="mono" title={task.workerId}>{task.workerType} · {task.workerId || "—"}</span><span className="mono">{task.durationSec == null ? "running" : `${task.durationSec}s`}</span><span className="mono">{task.source}</span></div>; }
function BackupRow({ backup }: { backup: PbsBackup }) { const tone = backupTone(backup); return <div className="alert-row" style={{ cursor: "default" }}><div className={"alert-sev " + tone}><Icon name={backup.backupType === "ct" ? "server" : "storage"} /></div><div className="alert-body"><div className="alert-hd"><span className="alert-title">{backup.backupType}/{backup.backupId}{backup.guestName ? ` · ${backup.guestName}` : ""}</span><Chip tone={tone}>{backup.verification}</Chip>{backup.protected && <Chip tone="ok">protected</Chip>}</div><div className="alert-meta"><span className="mono">{backup.source}</span><span className="dot-sep" /><span className="mono">ns:{backup.namespace}</span><span className="dot-sep" /><span className="mono">{backup.size}</span>{backup.guestNode && <><span className="dot-sep" /><span className="mono">{backup.guestServer}/{backup.guestNode}</span></>}</div></div><div className="alert-time"><span className="alert-ago">{ageLabel(backup.ageMin)}</span></div></div>; }
function DatastoreCard({ store }: { store: PbsDatastore }) { const tone = store.usedPct >= 85 ? "warn" : "ok"; return <div className="src-row"><div className="src-row-id"><div className="src-row-name"><StatusDot tone={tone} /> {store.store}</div><div className="src-row-host">{store.source} · {store.groups} groups · {store.snapshots} snapshots</div></div><Chip tone={tone}>{store.usedPct}% used</Chip><div className="src-row-actions" style={{ minWidth: 260 }}><Chip>{store.used} / {store.total}</Chip><Chip>{store.avail} free</Chip></div></div>; }
export default function Pbs({ snap, editMode, layoutStore, onLayoutChange, onConfigure }: { snap: Snapshot; editMode: boolean; layoutStore: LayoutStore; onLayoutChange: (pageId: string, layout: EditableLayoutValue) => void; onConfigure: () => void; }) {
  const sources = snap.sources.filter((s) => s.kind === "pbs"); const openAlerts = snap.alerts.alerts.filter((a) => a.status === "open" && a.source.toLowerCase() === "pbs"); const pbs = snap.pbs;
  const kpis = pbs.kpis.length ? pbs.kpis : [{ display: "0", unit: "", sub: "recent PBS snapshots indexed", trend: 0, spark: [] }, { display: "never", unit: "", sub: "latest successful backup", trend: 0, spark: [] }, { display: "0", unit: "%", sub: "highest datastore usage", trend: 0, spark: [] }, { display: "0", unit: "", sub: "missing/stale guests", trend: 0, spark: [] }];
  const cards = [
    ...KPI_LABELS.map((label, i) => ({ id: `kpi-${i}`, label, defaultSize: { w: 3, h: 1 }, minW: 2, maxW: 6, minH: 1, maxH: 1, content: <KpiTile label={label} kpi={kpis[i]} sparkColor={KPI_COLORS[i % KPI_COLORS.length]} /> })),
    { id: "coverage", label: "Backup Coverage", defaultSize: { w: 5, h: 5 }, minW: 4, minH: 4, content: <Card title="Backup Coverage" sub="Proxmox guests compared with PBS backup groups" tight><div className="kpi-grid" style={{ gridTemplateColumns: "repeat(4, 1fr)", padding: 14 }}><Chip tone="ok">{pbs.coverage.protected} protected</Chip><Chip tone={pbs.coverage.missing ? "crit" : "ok"}>{pbs.coverage.missing} missing</Chip><Chip tone={pbs.coverage.stale ? "warn" : "ok"}>{pbs.coverage.stale} stale</Chip><Chip>{pbs.coverage.orphaned} orphaned</Chip></div>{pbs.coverage.findings.length === 0 && <div className="empty-row" style={{ padding: 24 }}>No missing or stale backup coverage findings.</div>}{pbs.coverage.findings.slice(0, 8).map((f) => <div className="alert-row" key={f.id} style={{ cursor: "default" }}><div className={"alert-sev " + findingTone(f)}><Icon name="alert" /></div><div className="alert-body"><div className="alert-hd"><span className="alert-title">{f.title}</span></div><div className="alert-meta"><span>{f.detail}</span></div></div><div className="alert-time"><span className="alert-ago">{f.ageMin == null ? "—" : ageLabel(f.ageMin)}</span></div></div>)}</Card> },
    { id: "recent-backups", label: "Recent Backups", defaultSize: { w: 7, h: 7 }, minW: 5, minH: 4, content: <Card title="Recent Backups" sub="newest PBS snapshots, enriched with Proxmox guest names when possible" tight>{pbs.recentBackups.length === 0 && <div className="empty-row" style={{ padding: 36 }}>No PBS backups indexed yet.</div>}{pbs.recentBackups.slice(0, 18).map((b) => <BackupRow key={b.id} backup={b} />)}</Card> },
    { id: "datastores", label: "Datastores", defaultSize: { w: 6, h: 4 }, minW: 5, minH: 3, content: <Card title="Datastores" sub="capacity, groups and snapshot inventory" tight>{pbs.datastores.length === 0 && <div className="empty-row" style={{ padding: 28 }}>No datastores reported.</div>}{pbs.datastores.map((d) => <DatastoreCard key={`${d.source}:${d.store}`} store={d} />)}</Card> },
    { id: "tasks", label: "Recent PBS Tasks", defaultSize: { w: 6, h: 4 }, minW: 5, minH: 3, content: <Card title="Recent PBS Tasks" sub={`${pbs.failedTasks24h} failed in the last 24h`} tight><div className="log-stream" style={{ border: 0 }}>{pbs.recentTasks.length === 0 && <div className="empty-row" style={{ padding: 28 }}>No PBS task history indexed.</div>}{pbs.recentTasks.slice(0, 10).map((t) => <TaskRow key={t.id} task={t} />)}</div></Card> },
    { id: "sources-alerts", label: "Sources & Alerts", defaultSize: { w: 12, h: 4 }, minW: 6, minH: 3, content: <Card title="PBS Sources & Alerts" sub="API source health and currently open PBS alerts" actions={<button className="filter-pill" onClick={onConfigure}><Icon name="settings" /> Configure sources</button>} tight>{sources.length === 0 && <div className="empty-row" style={{ padding: 28 }}>No PBS source configured yet. Add one under Settings → Sources.</div>}{sources.map((s) => <div className="src-row" key={s.name}><div className="src-row-id"><div className="src-row-name"><StatusDot tone={s.ok ? "ok" : "crit"} /> {s.name}</div><div className="src-row-host">{s.detail}</div>{s.error && <div className="src-row-host" style={{ color: "var(--crit)" }}>{s.error}</div>}</div><Chip tone={s.ok ? "ok" : "crit"} dot>{s.ok ? "Online" : "Offline"}</Chip></div>)}{openAlerts.slice(0, 4).map((a) => <div className="alert-row" key={a.id} style={{ cursor: "default" }}><div className={"alert-sev " + a.sev}><Icon name="alert" /></div><div className="alert-body"><div className="alert-hd"><span className="alert-title">{a.title}</span></div><div className="alert-meta"><span className="mono">{a.target}</span><span className="dot-sep" /><span className="mono">{a.rule}</span></div></div></div>)}</Card> },
  ];
  return <div className="page"><EditableGrid pageId="pbs" items={cards} editMode={editMode} layoutStore={layoutStore} onLayoutChange={onLayoutChange} /></div>;
}
